import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";

import { Instrument_Sans } from "next/font/google"
import { TooltipProvider } from "@radix-ui/react-tooltip";
import LayoutContainerProvider from "@/components/containers/layoutcontainerprovider";

const font = Instrument_Sans({
  weight: ["400", "500", "600", "700"],
  display: "swap",
  subsets: ["latin-ext", "latin"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <TooltipProvider>
          <LayoutContainerProvider>
            {children}
          </LayoutContainerProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
